spin_manifest_version = 2

[application]
authors = ["Nate Cole Summers <nsummers72@gmail.com>"]
description = "A crossword helper boyfriend that uses AI to help you solve crosswords. It provides suggestions for words that fit the pattern you've entered, and it can also help you find the right word for a clue."
name = "crossword-bae"
version = "1.1.1"

[[trigger.http]]
route = "/..."
component = "fileserver"

# This serves the static files (HTML, CSS, etc.)
[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
files = [{ source = "assets", destination = "/" }]

[[trigger.http]]
route = "/api/question/..."
component = "helper"

# This is our function
[component.helper]
source = "target/crossword-helper.wasm"
exclude_files = ["**/node_modules"]
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
[component.helper.build]
command = "npm run build"
