spin_manifest_version = 2

[application]
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = ""
name = "crossword-helper"
version = "1.1.0"

[[trigger.http]]
route = "/..."
component = "fileserver"

# This serves the static files (HTML, CSS, etc.)
[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
files = [{ source = "assets", destination = "/" }]

[[trigger.http]]
route = "/api/question"
component = "helper"

# This is our function
[component.helper]
source = "target/crossword-helper.wasm"
exclude_files = ["**/node_modules"]
ai_models = ["llama2-chat"]
[component.helper.build]
command = "npm run build"
